/**
 * Class contains information about an individual solar panel.
 * Contains rated/actual efficiency, electricity generated, max output,
 * and whether or not the panel is working.
 * 
 * @author Jessica De Brito
 * @author Kal Pandit
 */
public class Panel {

    private double ratedEfficiency;
    private double actualEfficiency;
    private int electricityGenerated;
    private double maxOutput;
    private boolean isWorking;

    /**
     * Default constructor.
     */
    public Panel() {
        this.ratedEfficiency = 0;
        this.actualEfficiency = 0;
        this.electricityGenerated = 0;
        this.maxOutput = 350;
        this.isWorking = true;
    }

    /**
     * Constructs a new Panel with specified characteristics.
     *
     * @param ratedEfficiency  The efficiency rating of the panel.
     * @param actualEfficiency The actual efficiency of the panel in operation.
     * @param maxOutput        The maximum output capacity of the panel.
     * @param isWorking        The operational status of the panel.
     */
    public Panel(double ratedEfficiency, int maxOutput, boolean isWorking) {
        this.ratedEfficiency = ratedEfficiency;
        this.actualEfficiency = ratedEfficiency;
        this.electricityGenerated = 0;
        this.maxOutput = maxOutput;
        this.isWorking = isWorking;
    }

    /**
     * Gets the rated efficiency of the panel.
     *
     * @return The rated efficiency.
     */
    public double getRatedEfficiency() {
        return this.ratedEfficiency;
    }

    /**
     * Sets the rated efficiency of the panel.
     *
     * @param ratedEfficiency The new rated efficiency.
     */
    public void setRatedEfficiency(double ratedEfficiency) {
        this.ratedEfficiency = ratedEfficiency;
    }

    /**
     * Gets the actual efficiency of the panel.
     *
     * @return The actual efficiency.
     */
    public double getActualEfficiency() {
        return this.actualEfficiency;
    }

    /**
     * Sets the actual efficiency of the panel.
     *
     * @param actualEfficiency The new actual efficiency.
     */
    public void setActualEfficiency(double actualEfficiency) {
        this.actualEfficiency = actualEfficiency;
    }

    /**
     * Gets the maximum output capacity of the panel.
     *
     * @return The maximum output.
     */
    public double getMaxOutput() {
        return this.maxOutput;
    }

    /**
     * Sets the maximum output capacity of the panel.
     *
     * @param maxOutput The new maximum output.
     */
    public void setMaxOutput(double maxOutput) {
        this.maxOutput = maxOutput;
    }

    /**
     * Gets the electricity generated by the panel.
     *
     * @return The amount of electricity generated.
     */
    public int getElectricityGenerated() {
        return this.electricityGenerated;
    }

    /**
     * Sets the amount of electricity generated by the panel.
     *
     * @param electricityGenerated The new amount of electricity generated.
     */
    public void setElectricityGenerated(int electricityGenerated) {
        this.electricityGenerated = electricityGenerated;
    }

    /**
     * Checks if the panel is operational.
     *
     * @return true if the panel is working, false otherwise.
     */
    public boolean isWorking() {
        return this.isWorking;
    }

    /**
     * Sets the operational status of the panel.
     *
     * @param isWorking The new operational status.
     */
    public void setIsWorking(boolean isWorking) {
        this.isWorking = isWorking;
    }

    /**
     * Returns a string representation of the panel's attributes.
     *
     * @return A string representation of the panel.
     */
    public String toString() {
        String works = isWorking ? "Works" : "Broken";
        return "{" + ratedEfficiency + ", " + actualEfficiency + ", " + electricityGenerated + ", " + maxOutput + ", "
                + works + "}";
    }

}
